FROM node:22-alpine AS build

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG VITE_BACKEND_URL=/api
ARG VITE_F_API_KEY=
ARG VITE_F_AUTH_DOMAIN=
ARG VITE_F_PROJECT_ID=
ARG VITE_F_STORAGE_BUCKET=z
ARG VITE_F_MSG_SENDER_ID=
ARG VITE_F_APP_ID=
ARG VITE_F_MEASUREMENT_ID=

ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_F_API_KEY=$VITE_F_API_KEY
ENV VITE_F_AUTH_DOMAIN=$VITE_F_AUTH_DOMAIN
ENV VITE_F_PROJECT_ID=$VITE_F_PROJECT_ID
ENV VITE_F_STORAGE_BUCKET=$VITE_F_STORAGE_BUCKET
ENV VITE_F_MSG_SENDER_ID=$VITE_F_MSG_SENDER_ID
ENV VITE_F_APP_ID=$VITE_F_APP_ID
ENV VITE_F_MEASUREMENT_ID=$VITE_F_MEASUREMENT_ID

RUN pnpm build

FROM nginx:1.27-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

