import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import {
  AlertCircle,
  ArrowLeftRight,
  Ban,
  CheckCircle2,
  ShieldAlert,
  Sparkles,
} from 'lucide-react'
import axios from 'axios'
import { useMemo, useState } from 'react'

import {
  MessageDialog,
  type MessageDialogState,
} from '@/components/message-dialog'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import type {
  PlagiarismFlag,
  PlagiarismFlagStatus,
} from '@/models/plagiarism'
import { api, useIsAdmin } from '@/stores/userStore'

function formatDateTime(value: string | null) {
  if (!value) return 'Not reviewed yet'

  return new Intl.DateTimeFormat(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date(value))
}

function formatPercent(value: number) {
  return `${Math.round(value * 100)}%`
}

function formatDifficulty(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

function getStatusBadgeVariant(status: PlagiarismFlagStatus) {
  switch (status) {
    case 'reviewed':
      return 'default'
    case 'dismissed':
      return 'secondary'
    default:
      return 'destructive'
  }
}

export const Route = createFileRoute('/admin/plagiarism-flags')({
  component: RouteComponent,
})

function RouteComponent() {
  const isAdmin = useIsAdmin()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [statusFilter, setStatusFilter] =
    useState<PlagiarismFlagStatus | 'all'>('open')
  const [messageDialog, setMessageDialog] = useState<MessageDialogState | null>(
    null,
  )
  const [adminNotes, setAdminNotes] = useState<Record<string, string>>({})

  const flagsQuery = useQuery({
    queryKey: ['plagiarism-flags', statusFilter],
    enabled: isAdmin,
    queryFn: async () => {
      const { data } = await api.get<PlagiarismFlag[]>('/admin/plagiarism-flags', {
        params: {
          status: statusFilter,
        },
      })
      return data
    },
  })

  const refreshFlags = async () => {
    await queryClient.invalidateQueries({
      queryKey: ['plagiarism-flags'],
    })
  }

  const updateFlagMutation = useMutation({
    mutationFn: async ({
      flagId,
      status,
      adminNotes,
    }: {
      flagId: string
      status: PlagiarismFlagStatus
      adminNotes?: string
    }) => {
      const { data } = await api.patch<PlagiarismFlag>(
        `/admin/plagiarism-flags/${flagId}`,
        {
          status,
          adminNotes,
        },
      )
      return data
    },
    onSuccess: async () => {
      await refreshFlags()
    },
    onError: (error) => {
      const description = axios.isAxiosError(error)
        ? (error.response?.data?.message ?? 'Failed to update plagiarism flag.')
        : 'Failed to update plagiarism flag.'
      setMessageDialog({
        title: 'Update Failed',
        description,
        variant: 'destructive',
      })
    },
  })

  const filteredFlags = useMemo(() => flagsQuery.data ?? [], [flagsQuery.data])

  if (!isAdmin) {
    return (
      <main className="mx-auto flex w-full max-w-4xl flex-1 px-4 pb-16 pt-28">
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Admin Only</AlertTitle>
          <AlertDescription>
            Plagiarism moderation is only available to admins.
          </AlertDescription>
        </Alert>
      </main>
    )
  }

  return (
    <>
      <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-4 pb-16 pt-28">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="space-y-2">
            <Badge variant="outline">Admin moderation</Badge>
            <h1 className="text-3xl font-black tracking-tight">
              Plagiarism Flags
            </h1>
            <p className="max-w-3xl text-sm text-muted-foreground">
              Review suspiciously similar submissions generated by the plagiarism
              detection pipeline. These flags are assistive only and should be
              verified manually before any action is taken.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button asChild variant="outline">
              <Link to="/admin/review-reports">Review reports</Link>
            </Button>
            <Button asChild variant="outline">
              <Link to="/challenges">Back to challenges</Link>
            </Button>
          </div>
        </div>

        <Card>
          <CardHeader className="gap-3">
            <CardTitle className="text-base">Moderation filters</CardTitle>
            <CardDescription>
              Switch between open, reviewed, or dismissed plagiarism flags.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-3 sm:flex-row sm:items-center">
            <div className="w-full max-w-xs">
              <Select
                value={statusFilter}
                onValueChange={(value) =>
                  setStatusFilter(value as PlagiarismFlagStatus | 'all')
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Status filter" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="open">Open</SelectItem>
                  <SelectItem value="reviewed">Reviewed</SelectItem>
                  <SelectItem value="dismissed">Dismissed</SelectItem>
                  <SelectItem value="all">All</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="text-xs text-muted-foreground">
              {filteredFlags.length} flag{filteredFlags.length === 1 ? '' : 's'}
              {' '}loaded
            </div>
          </CardContent>
        </Card>

        {flagsQuery.isLoading ? (
          <Card>
            <CardContent className="py-6 text-sm text-muted-foreground">
              Loading plagiarism flags...
            </CardContent>
          </Card>
        ) : null}

        {!flagsQuery.isLoading && filteredFlags.length === 0 ? (
          <Card>
            <CardContent className="py-6 text-sm text-muted-foreground">
              No plagiarism flags match the current filter.
            </CardContent>
          </Card>
        ) : null}

        {filteredFlags.map((flag) => (
          <Card key={flag.id} className="gap-4">
            <CardHeader className="gap-3">
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div className="space-y-2">
                  <div className="flex flex-wrap items-center gap-2">
                    <ShieldAlert className="h-4 w-4 text-destructive" />
                    <CardTitle className="text-base">
                      #{flag.challengeId} {flag.challengeTitle}
                    </CardTitle>
                    <Badge variant={getStatusBadgeVariant(flag.status)}>
                      {flag.status}
                    </Badge>
                    <Badge variant="outline">{flag.language}</Badge>
                    <Badge variant="secondary">
                      {formatDifficulty(flag.challengeDifficulty)}
                    </Badge>
                  </div>
                  <CardDescription>
                    Pair: {flag.leftUsername} vs {flag.rightUsername} • Created{' '}
                    {formatDateTime(flag.createdAt)}
                  </CardDescription>
                </div>
                <div className="flex flex-col items-end gap-2">
                  <div className="text-right">
                    <div className="text-2xl font-black text-destructive">
                      {formatPercent(flag.suspicionScore)}
                    </div>
                    <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                      suspicion score
                    </div>
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() =>
                      navigate({
                        to: '/challenge',
                        search: { id: flag.challengeId },
                      })
                    }
                  >
                    Open challenge
                  </Button>
                </div>
              </div>
            </CardHeader>

            <CardContent className="space-y-5">
              <Alert>
                <Sparkles className="h-4 w-4" />
                <AlertTitle>Why this pair was flagged</AlertTitle>
                <AlertDescription>{flag.reason}</AlertDescription>
              </Alert>

              <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                <MetricCard
                  label="Rule score"
                  value={formatPercent(flag.ruleScore)}
                />
                <MetricCard
                  label="Normalized match"
                  value={formatPercent(flag.normalizedSimilarity)}
                />
                <MetricCard
                  label="Token overlap"
                  value={formatPercent(flag.tokenJaccard)}
                />
                <MetricCard
                  label="3-gram overlap"
                  value={formatPercent(flag.ngramJaccard)}
                />
              </div>

              <div className="grid gap-4 lg:grid-cols-2">
                <CodePanel
                  title={flag.leftUsername}
                  verdict={flag.leftVerdict}
                  sourceCode={flag.leftSourceCode}
                />
                <CodePanel
                  title={flag.rightUsername}
                  verdict={flag.rightVerdict}
                  sourceCode={flag.rightSourceCode}
                />
              </div>

              <div className="grid gap-3 md:grid-cols-[1fr_auto_auto] md:items-end">
                <label className="grid gap-2 text-sm">
                  <span className="font-medium">Admin notes</span>
                  <textarea
                    value={adminNotes[flag.id] ?? flag.adminNotes ?? ''}
                    onChange={(event) =>
                      setAdminNotes((current) => ({
                        ...current,
                        [flag.id]: event.target.value,
                      }))
                    }
                    rows={3}
                    className="min-h-24 w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-xs outline-none transition-[color,box-shadow] placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
                    placeholder="Add a moderation note for this flagged pair."
                  />
                </label>

                <Button
                  type="button"
                  className="gap-2"
                  onClick={() =>
                    updateFlagMutation.mutate({
                      flagId: flag.id,
                      status: 'reviewed',
                      adminNotes: adminNotes[flag.id] ?? flag.adminNotes ?? '',
                    })
                  }
                  disabled={updateFlagMutation.isPending}
                >
                  <CheckCircle2 className="h-4 w-4" />
                  Mark reviewed
                </Button>

                <Button
                  type="button"
                  variant="outline"
                  className="gap-2"
                  onClick={() =>
                    updateFlagMutation.mutate({
                      flagId: flag.id,
                      status: 'dismissed',
                      adminNotes: adminNotes[flag.id] ?? flag.adminNotes ?? '',
                    })
                  }
                  disabled={updateFlagMutation.isPending}
                >
                  <Ban className="h-4 w-4" />
                  Dismiss
                </Button>
              </div>

              <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground">
                <div className="flex flex-wrap items-center gap-4">
                  <span>Length ratio {formatPercent(flag.lengthRatio)}</span>
                  <span>Time gap {flag.hoursGap.toFixed(1)}h</span>
                  <span>Model {flag.modelVersion}</span>
                </div>
                <div>
                  Last review update: {formatDateTime(flag.reviewedAt)}
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </main>

      <MessageDialog
        message={messageDialog}
        onOpenChange={(open) => {
          if (!open) {
            setMessageDialog(null)
          }
        }}
      />
    </>
  )
}

function MetricCard({
  label,
  value,
}: {
  label: string
  value: string
}) {
  return (
    <div className="rounded-xl border border-border/70 bg-muted/10 p-4">
      <div className="text-[10px] font-semibold uppercase tracking-[0.25em] text-muted-foreground">
        {label}
      </div>
      <div className="mt-2 text-2xl font-black">{value}</div>
    </div>
  )
}

function CodePanel({
  title,
  verdict,
  sourceCode,
}: {
  title: string
  verdict: string
  sourceCode: string
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-border/70 bg-muted/10">
      <div className="flex items-center justify-between gap-2 border-b border-border/70 px-4 py-3">
        <div className="flex items-center gap-2 text-sm font-semibold">
          <ArrowLeftRight className="h-4 w-4 text-primary" />
          {title}
        </div>
        <Badge variant="secondary">{verdict}</Badge>
      </div>
      <pre className="max-h-80 overflow-auto p-4 text-xs leading-6 text-muted-foreground">
        <code>{sourceCode}</code>
      </pre>
    </div>
  )
}
