/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AchievementsIndexRouteImport } from './routes/achievements/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as ProfileCosmeticsRouteImport } from './routes/profile/cosmetics'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CosmeticIdRouteImport } from './routes/cosmetic/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminReviewReportsRouteImport } from './routes/admin/review-reports'
import { Route as AchievementsTypeRouteImport } from './routes/achievements/$type'
import { Route as ProfileEditIndexRouteImport } from './routes/profile/edit/index'
import { Route as AdminAchievementsNewRouteImport } from './routes/admin/achievements/new'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsIndexRoute = AchievementsIndexRouteImport.update({
  id: '/achievements/',
  path: '/achievements/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCosmeticsRoute = ProfileCosmeticsRouteImport.update({
  id: '/profile/cosmetics',
  path: '/profile/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticIdRoute = CosmeticIdRouteImport.update({
  id: '/cosmetic/$id',
  path: '/cosmetic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewReportsRoute = AdminReviewReportsRouteImport.update({
  id: '/admin/review-reports',
  path: '/admin/review-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsTypeRoute = AchievementsTypeRouteImport.update({
  id: '/achievements/$type',
  path: '/achievements/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditIndexRoute = ProfileEditIndexRouteImport.update({
  id: '/profile/edit/',
  path: '/profile/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAchievementsNewRoute = AdminAchievementsNewRouteImport.update({
  id: '/admin/achievements/new',
  path: '/admin/achievements/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/challenges': typeof ChallengesRoute
  '/cosmetics': typeof CosmeticsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/achievements/$type': typeof AchievementsTypeRoute
  '/admin/review-reports': typeof AdminReviewReportsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cosmetic/$id': typeof CosmeticIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/cosmetics': typeof ProfileCosmeticsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/achievements/new': typeof AdminAchievementsNewRoute
  '/profile/edit/': typeof ProfileEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/challenges': typeof ChallengesRoute
  '/cosmetics': typeof CosmeticsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/achievements/$type': typeof AchievementsTypeRoute
  '/admin/review-reports': typeof AdminReviewReportsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cosmetic/$id': typeof CosmeticIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/cosmetics': typeof ProfileCosmeticsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/achievements': typeof AchievementsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/admin/achievements/new': typeof AdminAchievementsNewRoute
  '/profile/edit': typeof ProfileEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/challenges': typeof ChallengesRoute
  '/cosmetics': typeof CosmeticsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/achievements/$type': typeof AchievementsTypeRoute
  '/admin/review-reports': typeof AdminReviewReportsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cosmetic/$id': typeof CosmeticIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/cosmetics': typeof ProfileCosmeticsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/achievements/new': typeof AdminAchievementsNewRoute
  '/profile/edit/': typeof ProfileEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenge'
    | '/challenges'
    | '/cosmetics'
    | '/home'
    | '/leaderboard'
    | '/achievements/$type'
    | '/admin/review-reports'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/cosmetic/$id'
    | '/demo/tanstack-query'
    | '/profile/$userId'
    | '/profile/cosmetics'
    | '/teams/$teamId'
    | '/achievements/'
    | '/admin/'
    | '/teams/'
    | '/admin/achievements/new'
    | '/profile/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenge'
    | '/challenges'
    | '/cosmetics'
    | '/home'
    | '/leaderboard'
    | '/achievements/$type'
    | '/admin/review-reports'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/cosmetic/$id'
    | '/demo/tanstack-query'
    | '/profile/$userId'
    | '/profile/cosmetics'
    | '/teams/$teamId'
    | '/achievements'
    | '/admin'
    | '/teams'
    | '/admin/achievements/new'
    | '/profile/edit'
  id:
    | '__root__'
    | '/'
    | '/challenge'
    | '/challenges'
    | '/cosmetics'
    | '/home'
    | '/leaderboard'
    | '/achievements/$type'
    | '/admin/review-reports'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/cosmetic/$id'
    | '/demo/tanstack-query'
    | '/profile/$userId'
    | '/profile/cosmetics'
    | '/teams/$teamId'
    | '/achievements/'
    | '/admin/'
    | '/teams/'
    | '/admin/achievements/new'
    | '/profile/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengeRoute: typeof ChallengeRoute
  ChallengesRoute: typeof ChallengesRoute
  CosmeticsRoute: typeof CosmeticsRoute
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  AchievementsTypeRoute: typeof AchievementsTypeRoute
  AdminReviewReportsRoute: typeof AdminReviewReportsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CosmeticIdRoute: typeof CosmeticIdRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileCosmeticsRoute: typeof ProfileCosmeticsRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  AchievementsIndexRoute: typeof AchievementsIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  AdminAchievementsNewRoute: typeof AdminAchievementsNewRoute
  ProfileEditIndexRoute: typeof ProfileEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/achievements'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AchievementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/cosmetics': {
      id: '/profile/cosmetics'
      path: '/profile/cosmetics'
      fullPath: '/profile/cosmetics'
      preLoaderRoute: typeof ProfileCosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetic/$id': {
      id: '/cosmetic/$id'
      path: '/cosmetic/$id'
      fullPath: '/cosmetic/$id'
      preLoaderRoute: typeof CosmeticIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review-reports': {
      id: '/admin/review-reports'
      path: '/admin/review-reports'
      fullPath: '/admin/review-reports'
      preLoaderRoute: typeof AdminReviewReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/$type': {
      id: '/achievements/$type'
      path: '/achievements/$type'
      fullPath: '/achievements/$type'
      preLoaderRoute: typeof AchievementsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit/': {
      id: '/profile/edit/'
      path: '/profile/edit'
      fullPath: '/profile/edit/'
      preLoaderRoute: typeof ProfileEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/achievements/new': {
      id: '/admin/achievements/new'
      path: '/admin/achievements/new'
      fullPath: '/admin/achievements/new'
      preLoaderRoute: typeof AdminAchievementsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengeRoute: ChallengeRoute,
  ChallengesRoute: ChallengesRoute,
  CosmeticsRoute: CosmeticsRoute,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  AchievementsTypeRoute: AchievementsTypeRoute,
  AdminReviewReportsRoute: AdminReviewReportsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CosmeticIdRoute: CosmeticIdRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileCosmeticsRoute: ProfileCosmeticsRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  AchievementsIndexRoute: AchievementsIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  AdminAchievementsNewRoute: AdminAchievementsNewRoute,
  ProfileEditIndexRoute: ProfileEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
